In [1]:
import numpy as np
from open3d import *

import sys
sys.path.append("/workspace/include")

from visualization_helper import *

%matplotlib inline

In [3]:
print("Testing IO for point cloud ...")
pcd = read_point_cloud("./../test.pcd")
print(pcd)
write_point_cloud("sample_secD.pcd", pcd)
write_point_cloud("test.pcd", pcd)

Testing IO for point cloud ...
PointCloud with 2750 points.


True

In [4]:
import k3d

In [5]:
pa = np.asarray(pcd.points)

plot = k3d.plot()

points_number = pa.shape[0]
colors = np.random.randint(0, 0xFFFFFF, points_number)

points = k3d.points(pa, colors, point_size=0.01, shader='3d')
plot += points
plot.camera_auto_fit = False
plot.display()

Output()

In [21]:
pa

array([[ 1.3579905 ,  4.00280809, -1.1325922 ],
       [ 3.33281803,  9.8181715 ,  0.18098146],
       [ 1.54550076,  4.55029202, -1.10945857],
       ...,
       [ 4.94497871, 12.22697258,  3.04493737],
       [ 4.00837469,  9.90613461, -0.18653132],
       [ 4.95058155, 12.22852612,  3.53495073]])

In [22]:
pcd = PointCloud()
pcd.points = Vector3dVector(pa)
write_point_cloud("pa2pcd.pcd", pcd)

True

In [23]:
pcd2 = read_point_cloud("pa2pcd.pcd")

IndexError: 

In [25]:
pcd2.colors

std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data.

# Cropping

In [12]:
vol = read_selection_polygon_volume("cropped.json")


In [13]:
chair = vol.crop_point_cloud(pcd)

In [15]:
chair

PointCloud with 0 points.

In [20]:
print("Recompute the normal of the downsampled point cloud")
estimate_normals(pcd, search_param = KDTreeSearchParamHybrid(
        radius = 0.1, max_nn = 30))

Recompute the normal of the downsampled point cloud


True

In [17]:
write_point_cloud("test.pcd", pcd)

True

True

In [3]:
print("Load a ply point cloud, print it, and render it")
pcd = read_point_cloud("sample_table.pcd")
print(pcd)
print(np.asarray(pcd.points))


Load a ply point cloud, print it, and render it
PointCloud with 460400 points.
[[-0.93387002 -0.6825     -1.18649995]
 [-0.93172997 -0.68322998 -1.18780005]
 [-0.92185003 -0.68054003 -1.18309999]
 ...
 [-0.12585001  0.38914001 -1.35699999]
 [-0.14683001  0.36662    -1.27849996]
 [-0.12884     0.37395999 -1.30410004]]


In [6]:
draw_geometries([pcd])

# Normal Estimation

In [8]:
normal = estimate_normals(pcd, search_param = KDTreeSearchParamHybrid(radius = 0.1, max_nn = 30))


In [9]:
type(normal)

bool

In [10]:
normal

True